export const demoData = {
  patients: [
    { patient_id: 'PAT-01', first_name: 'Raman', last_name: 'Nathan', city: 'Chennai', state: 'TN', gender: 'Male', policy_no: 'POL-1001' },
    { patient_id: 'PAT-02', first_name: 'Kavitha', last_name: 'Subramanian', city: 'Chennai', state: 'TN', gender: 'Female', policy_no: 'POL-1002' },
    { patient_id: 'PAT-03', first_name: 'Arun', last_name: 'Prakash', city: 'Chennai', state: 'TN', gender: 'Male', policy_no: 'POL-1003' },
    { patient_id: 'PAT-04', first_name: 'Deepa', last_name: 'Balaji', city: 'Madurai', state: 'TN', gender: 'Female', policy_no: null },
    { patient_id: 'PAT-05', first_name: 'Karthik', last_name: 'Raja', city: 'Tambaram', state: 'TN', gender: 'Male', policy_no: 'POL-1004' },
    { patient_id: 'PAT-06', first_name: 'Sangeetha', last_name: 'Mani', city: 'Coimbatore', state: 'TN', gender: 'Female', policy_no: 'POL-1005' },
    { patient_id: 'PAT-07', first_name: 'Venkatesh', last_name: 'Ramanujam', city: 'Trichy', state: 'TN', gender: 'Male', policy_no: null },
    { patient_id: 'PAT-08', first_name: 'Ananya', last_name: 'Vasudevan', city: 'Chennai', state: 'TN', gender: 'Female', policy_no: 'POL-1006' },
  ],
  appointments: [
    { appointment_id: 'APT-01', patient_name: 'Raman Nathan', doctor_name: 'Sundaram Krishnan', department: 'Cardiology', appointment_date: '2026-09-10T00:00:00.000Z', appointment_time: '10:00 AM', status: 'Completed', consultation_mode: 'Virtual' },
    { appointment_id: 'APT-02', patient_name: 'Kavitha Subramanian', doctor_name: 'Meenakshi Sundaram', department: 'Neurology', appointment_date: '2026-09-12T00:00:00.000Z', appointment_time: '11:30 AM', status: 'Scheduled', consultation_mode: 'Virtual' },
    { appointment_id: 'APT-03', patient_name: 'Arun Prakash', doctor_name: 'Vikram Ramanathan', department: 'Orthopedics', appointment_date: '2026-09-15T00:00:00.000Z', appointment_time: '02:00 PM', status: 'Scheduled', consultation_mode: 'In-Person' },
    { appointment_id: 'APT-04', patient_name: 'Deepa Balaji', doctor_name: 'Rajesh Venkataraman', department: 'General Medicine', appointment_date: '2026-09-10T00:00:00.000Z', appointment_time: '09:00 AM', status: 'Completed', consultation_mode: 'In-Person' },
    { appointment_id: 'APT-05', patient_name: 'Karthik Raja', doctor_name: 'Rajesh Venkataraman', department: 'General Medicine', appointment_date: '2026-09-11T00:00:00.000Z', appointment_time: '04:00 PM', status: 'Scheduled', consultation_mode: 'Virtual' },
    { appointment_id: 'APT-06', patient_name: 'Sangeetha Mani', doctor_name: 'Priya Dharshini', department: 'Dermatology', appointment_date: '2026-09-13T00:00:00.000Z', appointment_time: '03:00 PM', status: 'Scheduled', consultation_mode: 'Virtual' },
    { appointment_id: 'APT-07', patient_name: 'Venkatesh Ramanujam', doctor_name: 'Kalyan Sundaram', department: 'Gastroenterology', appointment_date: '2026-09-14T00:00:00.000Z', appointment_time: '10:30 AM', status: 'Scheduled', consultation_mode: 'In-Person' },
    { appointment_id: 'APT-08', patient_name: 'Ananya Vasudevan', doctor_name: 'Shalini Narayanan', department: 'Pulmonology', appointment_date: '2026-09-16T00:00:00.000Z', appointment_time: '11:00 AM', status: 'Scheduled', consultation_mode: 'Virtual' },
  ],
  prescriptions: [
    { prescription_no: 'RX-01', appointment_id: 'APT-01', patient_name: 'Raman Nathan', medicine_name: 'Amoxicillin', dosage: '500mg Twice Daily', duration_days: 5, quantity: 10, unit_price: 15.5, medicine_cost: 155 },
    { prescription_no: 'RX-01', appointment_id: 'APT-01', patient_name: 'Raman Nathan', medicine_name: 'Atorvastatin', dosage: '10mg Once Daily', duration_days: 30, quantity: 30, unit_price: 22, medicine_cost: 660 },
    { prescription_no: 'RX-02', appointment_id: 'APT-02', patient_name: 'Kavitha Subramanian', medicine_name: 'Paracetamol', dosage: '650mg As needed', duration_days: 3, quantity: 6, unit_price: 5, medicine_cost: 30 },
    { prescription_no: 'RX-03', appointment_id: 'APT-04', patient_name: 'Deepa Balaji', medicine_name: 'Azithromycin', dosage: '500mg Once Daily', duration_days: 5, quantity: 5, unit_price: 35, medicine_cost: 175 },
    { prescription_no: 'RX-04', appointment_id: 'APT-05', patient_name: 'Karthik Raja', medicine_name: 'Metformin', dosage: '500mg Twice Daily', duration_days: 30, quantity: 60, unit_price: 12, medicine_cost: 720 },
    { prescription_no: 'RX-05', appointment_id: 'APT-06', patient_name: 'Sangeetha Mani', medicine_name: 'Cetirizine', dosage: '10mg Once Daily', duration_days: 10, quantity: 10, unit_price: 6.5, medicine_cost: 65 },
    { prescription_no: 'RX-06', appointment_id: 'APT-07', patient_name: 'Venkatesh Ramanujam', medicine_name: 'Pantoprazole', dosage: '40mg Before Food', duration_days: 15, quantity: 15, unit_price: 18, medicine_cost: 270 },
    { prescription_no: 'RX-08', appointment_id: 'APT-03', patient_name: 'Arun Prakash', medicine_name: 'Ibuprofen', dosage: '400mg Post Meal', duration_days: 5, quantity: 10, unit_price: 8.5, medicine_cost: 85 },
  ],
  billing: [
    { invoice_no: 'INV-01', appointment_id: 'APT-01', patient_name: 'Raman Nathan', billing_date: '2026-09-10T00:00:00.000Z', stored_total: 1005, payment_status: 'Paid', calculated_total: 1665 },
    { invoice_no: 'INV-02', appointment_id: 'APT-02', patient_name: 'Kavitha Subramanian', billing_date: '2026-09-12T00:00:00.000Z', stored_total: 4500, payment_status: 'Pending', calculated_total: 4530 },
    { invoice_no: 'INV-03', appointment_id: 'APT-03', patient_name: 'Arun Prakash', billing_date: '2026-09-15T00:00:00.000Z', stored_total: 800, payment_status: 'Pending', calculated_total: 585 },
    { invoice_no: 'INV-04', appointment_id: 'APT-04', patient_name: 'Deepa Balaji', billing_date: '2026-09-10T00:00:00.000Z', stored_total: 950, payment_status: 'Paid', calculated_total: 625 },
    { invoice_no: 'INV-05', appointment_id: 'APT-05', patient_name: 'Karthik Raja', billing_date: '2026-09-11T00:00:00.000Z', stored_total: 1200, payment_status: 'Pending', calculated_total: 1320 },
    { invoice_no: 'INV-06', appointment_id: 'APT-06', patient_name: 'Sangeetha Mani', billing_date: '2026-09-13T00:00:00.000Z', stored_total: 1100, payment_status: 'Paid', calculated_total: 815 },
    { invoice_no: 'INV-07', appointment_id: 'APT-07', patient_name: 'Venkatesh Ramanujam', billing_date: '2026-09-14T00:00:00.000Z', stored_total: 1450, payment_status: 'Pending', calculated_total: 1170 },
    { invoice_no: 'INV-08', appointment_id: 'APT-08', patient_name: 'Ananya Vasudevan', billing_date: '2026-09-16T00:00:00.000Z', stored_total: 1350, payment_status: 'Pending', calculated_total: 950 },
  ],
}
